// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/kozmetika-naturalna",

  metadata: {
    title: "Guide till naturkosmetika | PerfuMaria das Ervas",
    description:
      "80 recept på 100 % naturlig kosmetika att göra hemma. Testade och beprövade formuleringar för eget bruk eller för att starta eget företag.",
  },

  hero: {
    headlineLine1: "80 recept på",
    headlineHighlight: "NATURKOSMETIKA",
    subheadline:
      "Få tillgång till hemliga recept på 100 % naturlig kosmetika som du kan skapa i hemmets lugna vrå! Testade och beprövade formuleringar för eget bruk eller för att starta ditt eget företag.",
    cta: "JAG VILL HA TILLGÅNG NU!",
    imageAlt: "Guide till naturkosmetika",
    timerLabels: {
      days: "Dagar",
      hours: "Timmar",
      minutes: "Minuter",
      seconds: "Sekunder",
    },
  },

  story: {
    text: "Nu ska jag ge dig en praktisk guide, rakt på sak och utan onödigt krångel, men extremt pålitlig så att du kan skapa din egen 100 % naturliga kosmetika hemma. Utan att spendera en förmögenhet, utan att vara beroende av tusentals ingredienser – med möjligheten att använda den själv, ge bort till nära och kära, eller till och med sälja om du vill skapa dig en ny inkomstkälla!",
    imageAlt: "Naturkosmetika",
  },

  recipeList: {
    headline: "Upptäck de",
    headlineHighlight: "80 recepten",
    headlineSuffix: "som du får tillgång till i Guiden till naturkosmetika:",
    cta: "JAG VILL HA DEM!",
    col1: [
      "Lugnande kroppskräm",
      "Kroppskräm med pantenol",
      "Uppfriskande kroppslotion",
      "Kroppssufflé",
      "Kroppssmör med annatto (urukum)",
      "Fast kroppssmör (Lotion bar)",
      "Kroppsolja",
      "Terapeutisk olja för bristningar och ärr",
      "Tvåfasig kroppsolja",
      "Naturlig sololja",
      "Flytande kroppstvål",
      "Duschgel",
      "Fast kroppstvål med SCI",
      "Traditionell hårdtvål",
      "Krämig fuktgivande tvål",
      "Exfolierande kroppstvål (Soap Body Scrub)",
      "Kroppsskrubb",
      "Kroppsskrubb med mandelmjöl",
      "Naturlig kroppshighlighter",
      "Body mist",
      "Ansiktskräm med C-vitamin",
      "After sun-ansiktskräm med lavendel",
      "Ansiktskräm med lera",
      "Återfuktande ansiktslotion med jasmin",
      "Torrolja för ansiktet (Dry Oil)",
      "Flytande ansiktstvål",
      "Rengöringsskum för ansiktet",
      "Ansiktsserum för torr och känslig hud",
      "Ansiktsserum för fet hud",
      "Ögonserum",
      "Ansiktsvatten för torr och känslig hud",
      "Uppfriskande ansiktsvatten för fet hud",
      "Rengöringsolja (Cleansing Oil)",
      "Rengöringsbalsam (Cleansing Balm)",
      "Tvål med röd lera – Detox och revitalisering",
      "Mild ansiktsskrubb",
      "Ansiktsgel med salicylsyra",
      "Gelmask med hyaluronsyra",
      "Rosenelixir för ansiktet",
      "Ansiktsspray med aloe vera",
      "Hårinpackning för lockigt och vågigt hår",
    ],
    col2: [
      "Hårinpackning för rakt och lätt vågigt hår",
      "Krämigt balsam",
      "Balsamkaka för lockigt och vågigt hår",
      "Balsamkaka för rakt och lätt vågigt hår",
      "Schampokaka för lockigt och vågigt hår",
      "Schampokaka för rakt och lätt vågigt hår",
      "Flytande schampo",
      "Krämigt 2-i-1-schampo",
      "Barnschampo",
      "Leave-in-balsam",
      "Värmeskyddande hårspray",
      "Hårolja",
      "Hårgelé",
      "Naturlig hårpomada",
      "Återfuktande finishspray",
      "Skalpskrubb",
      "Hårtonic för ökad hårväxt",
      "Serum för kluvna toppar",
      "Hårparfym",
      "Naturlig intimtvål",
      "Naturlig barntvål för kroppen",
      "Naturlig flytande parfym",
      "Naturlig fast parfym",
      "Tandkräm i gelform",
      "Munskölj",
      "Deodorantspray",
      "Ringblomssalva",
      "Arnikasalva",
      "Vårdande läppbalsam",
      "Naturligt läppstift",
      "Naturlig läppskrubb",
      "Sminkborttagningsspray",
      "Raklödder",
      "Naturlig aftershave",
      "Hand- och fotkräm",
      "Ögonbrynsgel",
      "Naturligt massageljus",
      "Vårdande nagel- och nagelbandsserum",
      "Naturligt myggmedel",
      "Revitaliserande badsalt",
    ],
  },

  whatYouGet: {
    headline: "VAD HITTAR DU I DENNA KOMPLETTA GUIDE?",
    cta: "SKAFFA GUIDEN NU!",
    imageAlt: "Vad du hittar i guiden",
    items: [
      "Över 80 testade och beprövade recept – inklusive krämig exfolierande tvål, torrolja för ansiktet, body mist, värmeskydd för håret och flera andra nya formuleringar.",
      "Baser för krämer, geler, schampon och tvålar – lär dig skapa säkra och skräddarsydda formuleringar för varje hud- och hårtyp.",
      "En komplett steg-för-steg-guide för både nybörjare och experter – behärska allt från grundläggande koncept till de mest avancerade teknikerna.",
      "Ingredienslexikon – upptäck fördelarna med olika naturliga råvaror för att kunna skapa högpresterande kosmetika.",
      "Fytoterapi inom kosmetologin – hur du använder medicinalväxter för att förstärka effekten av dina produkter.",
      "Hemligheterna bakom naturliga formuleringar – pH-justering, konservering, val av råvaror och effektiva kombinationer.",
      "Tips för hemmatillverkning och professionell produktion – skapa din egen lilla verkstad för naturkosmetika och förfina dina tekniker.",
      "Hållbarhet och miljöhänsyn – lär dig skapa biologiskt nedbrytbar och miljövänlig kosmetika.",
    ],
  },

  testimonials: {
    headline: "SE VAD ANDRA SÄGER OM GUIDEN TILL NATURKOSMETIKA:",
    cta: "JAG VILL HA TILLGÅNG NU!",
    cards: [
      {
        name: "Maja S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Jag älskar den här guiden! Har redan gjort den lugnande kroppskrämen och ansiktstvålen, de blev helt fantastiska. Mycket bättre än de industriella produkterna jag använde förut. Rekommenderas starkt!",
        source: "WhatsApp",
      },
      {
        name: "Elin G.",
        initials: "EG",
        color: "#0f766e",
        stars: 5,
        text: "Hörni, vilken underbar guide! Recepten är väldigt detaljerade och lätta att följa. Jag har redan sålt några produkter till mina vänner och de älskar dem. Värd varenda krona!",
        source: "WhatsApp",
      },
      {
        name: "Sofia R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Jag tvekade först, men det var det verkligen värt! Råvarulexikonet hjälpte mig enormt mycket att förstå ingredienserna. Har redan gjort 6 olika recept och alla blev perfekta.",
        source: "WhatsApp",
      },
      {
        name: "Daniela M.",
        initials: "DM",
        color: "#b45309",
        stars: 5,
        text: "Vilken fantastisk investering! Med guiden lärde jag mig att göra schampo- och balsamkakor. Mitt hår mår mycket bättre och jag sparar massor av pengar varje månad. Tack!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Med Guiden till naturkosmetika lär du dig att skapa din kosmetika från grunden.",
    text2: "Den visar dig steg-för-steg hur du väljer naturliga ingredienser, anpassar formuleringarna för olika hud- och hårtyper och skräddarsyr produkterna helt efter dina egna behov.",
    text3: "Dessutom får du självförtroende och blir självständig i ditt skapande, vilket gör att du kan testa och anpassa recepten för att ta fram unika produkter med din egen signatur. Tack vare det detaljerade lexikonet över naturliga råvaror lär du känna de allra bästa ingredienserna och hittar den perfekta kombinationen för varje specifik produkt.",
    cta: "SKAFFA GUIDEN NU!",
    imageAlt: "Självständighet inom naturkosmetika",
  },

  benefitsList: {
    headline: "Oberoende och kreativitet inom naturkosmetika!",
    cta: "JAG VILL HA TILLGÅNG NU!",
    items: [
      {
        bold: "Lär dig skapa",
        rest: " krämer, serum, schampon, tvålar och mycket mer.",
      },
      {
        bold: "Upptäck hur du väljer",
        rest: " helt rätt ingredienser för varje behov.",
      },
      {
        bold: "Bli oberoende av den industriella kosmetikan och",
        rest: " utveckla dina egna skräddarsydda formuleringar.",
      },
      {
        bold: "Fördjupa dig i fytoterapin inom kosmetologin,",
        rest: " och dra nytta av medicinalväxternas terapeutiska egenskaper.",
      },
      {
        bold: "Sänk dina kostnader",
        rest: " genom att tillverka din egen kosmetika, utan att någonsin kompromissa med kvaliteten.",
      },
      {
        bold: "Få tillgång till professionella formuleringar",
        rest: " och lär dig att säkert skapa de absolut bästa produkterna.",
      },
      {
        bold: "Stick ut på marknaden för naturlig skönhet,",
        rest: " som växer ständigt och värderar hållbara produkter högt.",
      },
      {
        bold: "Lär dig sätta upp en kosmetikverkstad hemma,",
        rest: " med praktiska tips för hur du organiserar din arbetsyta.",
      },
    ],
  },

  economy: {
    headline: "Besparingar och affärsmöjligheter på den naturliga marknaden!",
    text1: "Att skapa din egen naturkosmetika är en fantastisk möjlighet både för att spara pengar och för att starta ett eget företag. Med Guiden till naturkosmetika lär du dig tillverka högkvalitativa produkter till en låg kostnad. Du slipper betala överpriser för konventionella produkter och investerar istället i prisvärda och extremt effektiva naturliga ingredienser.",
    text2: "Om du vill starta eget är detta en ovärderlig guide för att bygga upp en hållbar och lönsam verksamhet. Med exklusiva formuleringar och praktiska råd om konservering, förpackning och marknadsföring kan du skapa ditt alldeles egna varumärke och erbjuda handgjorda produkter som ligger helt rätt i tiden för en medveten och ekologisk konsumtion.",
    cta: "SKAFFA GUIDEN NU!",
    imageAlt: "Affärsmöjligheter på den naturliga marknaden",
  },

  finalCta: {
    urgencyLabel: "SISTA DAGEN ATT BESTÄLLA",
    urgencySub: "till kampanjpris!",
    urgencyText:
      "Det här är din absolut sista chans att ta del av vårt specialerbjudande och bli en av våra tusentals nöjda deltagare!",
    offerPrice: "99 kr",
    button: "FÅ TILLGÅNG NU!",
    productTitle: "Guide till naturkosmetika!",
    imageAlt: "Guide till naturkosmetika",
    bundleList: [
      "80 recept på naturkosmetika",
      "Komplett studiematerial",
      "Lärorikt råvarulexikon",
      "Community för deltagare",
      "Dedikerad support för dina frågor",
      "Leverantörslista",
    ],
    timerLabels: {
      days: "Dagar",
      hours: "Timmar",
      minutes: "Minuter",
      seconds: "Sekunder",
    },
  },

  footer: {
    tagline: "Upptäck hur du skapar den perfekta naturkosmetikan!",
    linkLabel: "Komplett kurs i naturkosmetika",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};